### ISSUE TITLE
Can`t build when download python

### ISSUE THREAD

**Issue by bailehang** [NVIDIAGameWorks/GettingStartedWithRTXRayTracing#1]
Fetching python@2.7.14-windows-x86_32.zip from S3 ...
Connecting to S3 ...
Downloading ...
Unpacking Python interpreter ...

How to solve the problem? Thanks.

**Comment by bailehang** [comment]
The download succeeded after several attempts, but there was another error

1>------ Build started: Project: Tutor01-OpenWindow, Configuration: Release x64 ------
1>Processing project file 'F:\DEMO\GettingStartedWithRTXRayTracing\Falcor\dependencies.xml'
1>Package 'glm' at version '0.9.8.5' is missing from local storage.
1>Downloading from 'd4i3qtqj3r0z5.cloudfront.net': glm@0.9.8.5.7z (153 KiB)
1>No continuous progress report because this is not a proper terminal. Be patient ...
1>100% (speed 1.44 MiB/s)
1>Total of 0.10 seconds
1>Decompressing: glm@0.9.8.5.7z (153 KiB)
1>No continuous progress report because this is not a proper terminal. Patience is a virtue ...
1>100% (speed 2.52 MiB/s)
1>Total of 0.72 seconds
1>Output size: 1.80 MiB
1>Generating checksum for installed package ...
1>Traceback (most recent call last):
1>  File "F:\packman-repo\packman-common\5.3.1\packman.py", line 1012, in <module>
1>    main()
1>  File "F:\packman-repo\packman-common\5.3.1\packman.py", line 993, in main
1>    return args.func(**vars(args))
1>  File "F:\packman-repo\packman-common\5.3.1\packman.py", line 465, in pull_cmd
1>    variable_file)
1>  File "F:\packman-repo\packman-common\5.3.1\packman.py", line 499, in pull_with_variable_file
1>    pull_dependencies(deps, remote_configs, remote_names, platform, postscript, variable_file)
1>  File "F:\packman-repo\packman-common\5.3.1\packman.py", line 580, in pull_dependencies
1>    packager.install_package(target_filename, install_path)
1>  File "F:\packman-repo\packman-common\5.3.1\packager.py", line 203, in install_package
1>    staging_dir.promote_and_rename(version)
1>  File "F:\packman-repo\packman-common\5.3.1\utils.py", line 78, in promote_and_rename
1>    os.rename(self.temp_folder_path, abs_dst_folder_name)
1>WindowsError: [Error 5]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "call F:\DEMO\GettingStartedWithRTXRayTracing\\Falcor\Framework\\BuildScripts\prebuild.bat F:\DEMO\GettingStartedWithRTXRayTracing\\Falcor\Framework\ F:\DEMO\GettingStartedWithRTXRayTracing\ F:\DEMO\GettingStartedWithRTXRayTracing\01-OpenWindow\ x64 x64 Release F:\DEMO\GettingStartedWithRTXRayTracing\Bin\x64\Release\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "01-OpenWindow.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by erich666** [comment]
See the "Troubleshooting:" section of the README page at https://github.com/NVIDIAGameWorks/GettingStartedWithRTXRayTracing

This talks about MSB3073. You may need to get the Falcor distribution again, if the directories did not get set up correctly. I found that my **delete_dependencies.bat** file has a bug - fixed, and get the new one [here](https://github.com/NVIDIAGameWorks/GettingStartedWithRTXRayTracing/blob/master/Falcor/delete_dependencies.bat). Then run **update_dependencies.bat** again, before running the build.

**Comment by bailehang** [comment]
I recompiled Falcor and copy the lib, It can work now. Thanks

**Comment by erich666** [comment]
Good, glad it worked out at last. I definitely recommend the Release version for faster load speed, especially with Sphereflake.

**Comment by bailehang** [comment]
Hi, erich666, All tutors are available on my machine ( GTX 2080 ), but there's a problem with DXR-Sphereflake and DXR-RayTracingInOneWeekend.

When the program is initialized, the device instance is paused. 
pDevice->CreateCommittedResource(&heapProps, D3D12_HEAP_FLAG_NONE, &bufDesc, d3dState, nullptr, IID_PPV_ARGS(&pApiHandle)

I guess it used the wrong graphics card. When I was debugging the program in DEBUG model, the Falcor.lib(3.0.7 the latest version) lack of an interface, can you provide an up-to-date the debug Falcor.lib? Thanks.

SphereflakeDemoPass.obj : error LNK2019: unresolved external symbol "public: static class std::shared_ptr<class Falcor::Mesh> __cdecl Falcor::Mesh::createFromBoundingBoxBuffer(class std::shared_ptr<class Falcor::Buffer> const &,unsigned int,class std::shared_ptr<class Falcor::Material> const &)" (?createFromBoundingBoxBuffer@Mesh@Falcor@@SA?AV?$shared_ptr@VMesh@Falcor@@@std@@AEBV?$shared_ptr@VBuffer@Falcor@@@4@IAEBV?$shared_ptr@VMaterial@Falcor@@@4@@Z) referenced in function "protected: void __cdecl SphereflakeDemo::buildScene(void)" (?buildScene@SphereflakeDemo@@IEAAXXZ)

**Comment by erich666** [comment]
As it says on https://github.com/NVIDIAGameWorks/GettingStartedWithRTXRayTracing

> The Release versions will compile and link with the files in this distribution. To link the Debug versions:
> Download http://www.realtimerendering.com/downloads/nvidia/Falcor.lib and put it in the directory GettingStartedWithRTXRayTracing\Falcor\Framework\Lib\debugdxr.

Or simply compile and run the Release version.
