### ISSUE TITLE
Sphereflake

### ISSUE THREAD

**Issue by corredD** [NVIDIAGameWorks/GettingStartedWithRTXRayTracing#13]
![CaptureErr2](https://user-images.githubusercontent.com/539461/97060417-18a18800-1548-11eb-929e-548222c8001a.PNG)
![CaptureError](https://user-images.githubusercontent.com/539461/97060418-193a1e80-1548-11eb-9275-298e1f03dfe3.PNG)

Any chance that someone would fix the Sphereflake demo  ? I tried to manually add the raytraced AABB and fix all errors. But still, even after successful compilation, the executable complains and I have truly no idea what's the problem. Or anyone already tried and could point me on the right direction ?
Having that demo running would be astonishing, especially from the claim from the blog of the 48 million spheres...

**Comment by erich666** [comment]
Thanks for asking. I'm hoping to get back to this code in November. Factor changed considerably, losing the ability for custom intersection shaders, then gaining it again. So, I'd like to use the new Falcor code and get this one going again.

**Comment by corredD** [comment]
Thanks for your quick reply, that would be fantastic, I am crossing my finger you will have time to look at it.

**Comment by erich666** [comment]
I had hopes of attacking this one come the new year, now that my Mineways PBR project is wrapping up, but duty calls - I'm getting pulled into a new project. [Falcor](https://github.com/NVIDIAGameWorks/Falcor) does have a new version out, and I believe it now (or will) again support custom intersection shaders, such as for sphere intersection. Unfortunately I don't have the cycles to actually move sphereflake to the new Falcor.

But, the moral of this story is that the new Falcor is worth a look.
