### ISSUE TITLE
Falcor 4.4 build system has changed

### ISSUE THREAD

**Issue by bipul-mohanto** [NVIDIAGameWorks/GettingStartedWithRTXRayTracing#14]
Hello, This is actually not a technical issue. I guess the instruction set for Falcor in `Readme.md` has changed a lot for the latest Falcor 4.4.

**Comment by erich666** [comment]
Thanks. This code base is pretty out-of-date, I'd be surprised if it still works with the latest Falcor. The code still has some use to it, but we need to at least note that it won't work as-is. I'll try to update it in some way soon.
