### ISSUE TITLE
Package '7za' at version '16.02.2' is missing from local storage

### ISSUE THREAD

**Issue by BigNoobDog** [NVIDIAGameWorks/GettingStartedWithRTXRayTracing#2]
When i was running 'update_dependencies.bat',  cmd reported this. I searched for this issues on last project 'NVIDIAGameWorks/Falcor', halldorfannar told to update packman to 5.1. Should i download 'NVIDIAGameWorks/Falcor' package to solve this?

**Comment by BigNoobDog** [comment]
I also installed the 7-Zip 16.02 version

**Comment by erich666** [comment]
I think I would try again, i.e., run **delete_dependencies.bat** and try **update_dependencies.bat** again. I have not run into the error you mention. I suspect it is a sign of a bad/incomplete download.
